'use strict';
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let active='ask';const titles={ask:'Evidence Q&A',data:'Knowledge base',architecture:'Pipeline & configuration',entities:'Architecture records',impact:'Dependency & impact',compare:'Revision comparison',consistency:'Consistency review',evaluation:'Evaluation evidence'};
const citation=id=>`<button class="citation" data-citation="${esc(id)}">${esc(id)} · inspect source ↗</button>`;
async function api(path,body){const r=await fetch(path,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{});const d=await r.json();if(!r.ok)throw Error(d.error||'Request failed');return d}
function card(title,body,extra=''){return `<div class="card ${extra}"><h2>${esc(title)}</h2>${body}</div>`}
function table(headers,rows){return `<table><thead><tr>${headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table>`}
function version(){return $('#version').value}
async function show(tab){active=tab;$('#title').textContent=titles[tab];document.querySelectorAll('.panel').forEach(x=>x.classList.toggle('active',x.id===tab));document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x.dataset.tab===tab));$('#error').textContent='';if(tab==='ask')return;const target=$('#'+tab);target.innerHTML='<p class="subtle">Loading local evidence…</p>';try{
if(tab==='data'){const d=await api('/api/data');target.innerHTML='<div class="grid">'+d.documents.map(x=>`<div class="stat"><strong>${esc(x.version)}</strong><span>${esc(x.document_id)} · ${x.size_bytes} bytes · synthetic</span></div>`).join('')+`<div class="stat"><strong>${d.chunks.length}</strong><span>Version-specific evidence chunks</span></div></div>`+card('Source records',d.chunks.filter(x=>x.version===version()).map(c=>`<h3>${esc(c.section)}</h3><pre>${esc(c.text)}</pre>${citation(c.id)}`).join(''))}
if(tab==='architecture'){const [d,s]=await Promise.all([api('/api/architecture'),api('/api/status')]);target.innerHTML=card('Executed pipeline',`<div class="steps">${d.steps.map(x=>`<div class="step">${esc(x)}</div>`).join('')}</div>`)+card('Current configuration',`<p class="subtle">Offline extractive mode has no pretrained generation model. Local pretrained mode requires installation and separate evaluation.</p><pre>${esc(JSON.stringify(s.config,null,2))}</pre>`)}
if(tab==='entities'){const es=await api('/api/entities?version='+version());target.innerHTML=card(`${es.length} extracted records`,table(['Kind','Name','Attributes','Evidence'],es.map(e=>[esc(e.kind),esc(e.name),esc(Object.entries(e.attributes).map(([k,v])=>k+': '+v).join(' · ')),citation(e.citation)])))+card('Export analysis','<button id="export" class="primary">Download cited JSON</button>')}
if(tab==='impact'){const g=await api('/api/graph?version='+version());target.innerHTML=card('Declared signal dependencies',g.edges.map(e=>`<div class="impact-path"><span class="node">${esc(e.source)}</span><span>→ ${esc(e.signal)} →</span><span class="node">${esc(e.target)}</span></div>${citation(e.citation)}<br>`).join(''))+card('Potential downstream impact',`<p class="subtle">Reachability follows declared signal direction. This does not establish a defect or risk score.</p><select id="component">${g.nodes.map(n=>`<option>${esc(n)}</option>`).join('')}</select><button id="run-impact" class="primary">Trace impact →</button><div id="impact-result"></div>`);$('#component').value='VehicleStateProvider'}
if(tab==='compare'){const d=await api('/api/compare');target.innerHTML=card(`${d.from_version} → ${d.to_version} · ${d.changes.length} record changes`,d.changes.map(c=>`<h3>${esc(c.kind.toUpperCase())} · ${esc(c.entity)}</h3>${c.before?`<pre>Before: ${esc(JSON.stringify(c.before.attributes))}\nAfter: ${esc(JSON.stringify(c.after.attributes))}</pre>${citation(c.before.citation)}${citation(c.after.citation)}`:`<pre>${esc(JSON.stringify(c.record.attributes))}</pre>${citation(c.record.citation)}`}`).join(''))}
if(tab==='consistency'){const d=await api('/api/consistency?version='+version());target.innerHTML=card(`${d.findings.length} finding${d.findings.length===1?'':'s'} · ${version()}`,d.findings.length?d.findings.map(f=>`<h3>${esc(f.entity)} · ${esc(f.rule)}</h3><p>${esc(f.details)}</p>${citation(f.citation)}`).join(''):'<p>No findings under the three implemented rules.</p>','findings')+card('Review boundary',`<p>${esc(d.limitation)}</p><p class="subtle">Rules: ${esc(d.rules.join(', '))}. Findings require engineer confirmation.</p>`)}
if(tab==='evaluation'){const d=await api('/api/evaluation');target.innerHTML=`<div class="grid"><div class="stat"><strong>${d.qa?.passed??'—'} / ${d.qa?.total??'—'}</strong><span>QA scenarios passed</span></div><div class="stat"><strong>${d.retrieval?.hit_rate_at_k!=null?(100*d.retrieval.hit_rate_at_k).toFixed(1)+'%':'—'}</strong><span>Reference evidence hit rate</span></div><div class="stat"><strong>${d.latency?.median_ms??'—'} ms</strong><span>Median QA latency</span></div></div>`+card('Actual measured results',`<p class="subtle">Synthetic dataset only. Citation copying is source traceability, not an independent semantic faithfulness benchmark.</p><pre>${esc(JSON.stringify(d,null,2))}</pre>`)}
}catch(e){target.innerHTML='';$('#error').textContent=e.message}}
async function ask(){const q=$('#question').value;const btn=$('#ask-button');btn.disabled=true;$('#error').textContent='';try{const d=await api('/api/ask',{question:q,version:version()});$('#answer').innerHTML=card(d.status==='answered'?'Retrieved answer':'Evidence boundary',`<div class="result-head"><p>${esc(d.backend)} · ${d.latency_ms} ms · ${esc(d.version)}</p><span class="badge">Review required</span></div>${d.reason?`<p>${esc(d.reason)}</p>`:d.claims.map(c=>`<div class="claim">${esc(c.text)}${citation(c.citation)}</div>`).join('')}<p class="subtle">${esc(d.warning)}</p>`)+(d.evidence.length?card('Retrieval trace',table(['Evidence','Score','Section'],d.evidence.map(c=>[citation(c.id),esc(c.score),esc(c.section)]))):'')}catch(e){$('#error').textContent=e.message}finally{btn.disabled=false}}
$('#question-form').addEventListener('submit',e=>{e.preventDefault();ask()});document.querySelectorAll('nav button').forEach(b=>b.addEventListener('click',()=>show(b.dataset.tab)));$('#version').addEventListener('change',()=>{if(active==='ask')$('#answer').innerHTML='<p class="subtle">Source changed. Ask again to retrieve the selected version.</p>';else show(active)});
document.addEventListener('click',async e=>{try{if(e.target.dataset.question){$('#question').value=e.target.dataset.question;await ask()}
if(e.target.dataset.citation){const d=await api('/api/source?id='+encodeURIComponent(e.target.dataset.citation));$('#source-title').textContent=d.section;$('#source-meta').textContent=`${d.document_id} · ${d.version} · page ${d.page??'not asserted'} · ${d.filename}`;$('#source-text').textContent=d.text;$('#source-dialog').showModal()}
if(e.target.id==='run-impact'){const d=await api('/api/impact?version='+version()+'&component='+encodeURIComponent($('#component').value));$('#impact-result').innerHTML=`<p>${d.affected.length} potentially affected component(s)</p>`+d.affected.map(a=>`<h3>${esc(a.component)}</h3><p class="subtle">${esc(a.path.map(p=>p.source+' → '+p.target).join(' ; '))}</p>${a.path.map(p=>citation(p.citation)).join('')}`).join('')}
if(e.target.id==='export'){const d=await api('/api/export?version='+version());const u=URL.createObjectURL(new Blob([JSON.stringify(d,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download='AutoArch_AI_Analysis_'+version()+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}}catch(err){$('#error').textContent=err.message}});
$('#close-source').addEventListener('click',()=>$('#source-dialog').close());api('/api/status').then(d=>{$('#backend').textContent=d.backend==='extractive'?'Offline · extractive':'Local pretrained model'}).catch(e=>$('#error').textContent=e.message);
